# Generated by Django 4.2.6 on 2023-11-23 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="student",
            new_name="students",
        ),
    ]
